behaviors:
  Spider:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 327680
      learning_rate: 1e-5
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
      memory:
        memory_size: 512
        sequence_length: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: True
          hidden_units: 512
          num_layers: 5
          vis_encode_type: simple
          memory:
            memory_size: 512
            sequence_length: 128
      curiosity:
        gamma: 0.995
        strength: 0.1
        learning_rate: 1e-5
        network_settings:
          normalize: True
          hidden_units: 512
          num_layers: 5
    keep_checkpoints: 20
    even_checkpoints: True
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 1024
    summary_freq: 50000
    # threaded: True
